name: tongtu
description: "通途（Tongtu）——基于 Flutter + 官方 mihomo 内核的跨平台代理工具"
publish_to: 'none' # 私有应用，不发布到 pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
