// GENERATED — DO NOT EDIT. 由 tokens/*.json 生成（node build.mjs），与 Flutter/CSS 同源。
export const colorsLight = {
  primary: '#3f51b5',
  onPrimary: '#ffffff',
  primaryContainer: '#e0e2fb',
  onPrimaryContainer: '#161a4e',
  secondary: '#1e9bd4',
  onSecondary: '#ffffff',
  secondaryContainer: '#d7eef9',
  onSecondaryContainer: '#0a5b7a',
  surface: '#ffffff',
  onSurface: '#1a1c2a',
  surfaceVariant: '#edeef6',
  onSurfaceVariant: '#45464f',
  background: '#f6f7fb',
  onBackground: '#1a1c2a',
  outline: '#c4c6d0',
  error: '#ba1a1a',
  onError: '#ffffff',
} as const;

export const colorsDark = {
  primary: '#bbc3ff',
  onPrimary: '#1a2270',
  primaryContainer: '#2b3590',
  onPrimaryContainer: '#e0e2fb',
  secondary: '#8dd2f2',
  onSecondary: '#06384b',
  secondaryContainer: '#143c4e',
  onSecondaryContainer: '#bce7fb',
  surface: '#15161b',
  onSurface: '#e4e2e9',
  surfaceVariant: '#45464f',
  onSurfaceVariant: '#c4c6d0',
  background: '#0f1014',
  onBackground: '#e4e2e9',
  outline: '#8e9099',
  error: '#ffb4ab',
  onError: '#690005',
} as const;

export const dims = {
  spaceNone: 0,
  spaceXs: 4,
  spaceSm: 8,
  spaceMd: 12,
  spaceLg: 16,
  spaceXl: 24,
  space2xl: 32,
  space3xl: 48,
  radiusNone: 0,
  radiusXs: 4,
  radiusSm: 8,
  radiusMd: 12,
  radiusLg: 16,
  radiusXl: 28,
  radiusFull: 9999,
  fontXs: 12,
  fontSm: 14,
  fontMd: 16,
  fontLg: 20,
  fontXl: 24,
  font2xl: 32,
} as const;
